### ISSUE TITLE
Ошибка при открытии WFS с недостатком прав

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis_connect#1]
```
Traceback (most recent call last):
  File "/home/trolleway/.qgis2/python/plugins/ngw_connect/ngw_api/qt/qt_ngw_resource_model.py", line 45, in rowCount
    return parent_item.get_children_count()
  File "/home/trolleway/.qgis2/python/plugins/ngw_connect/ngw_api/qt/qt_ngw_resource_item.py", line 54, in get_children_count
    self._load_children()
  File "/home/trolleway/.qgis2/python/plugins/ngw_connect/ngw_api/qt/qt_ngw_resource_item.py", line 58, in _load_children
    resource_children = self._ngw_resource.get_children()
  File "/home/trolleway/.qgis2/python/plugins/ngw_connect/ngw_api/core/ngw_resource.py", line 95, in get_children
    children.append(self._res_factory.get_resource_by_json(child_json))
  File "/home/trolleway/.qgis2/python/plugins/ngw_connect/ngw_api/core/ngw_resource_factory.py", line 60, in get_resource_by_json
    return self.__res_types_register[res_json['resource']['cls']](self, res_json)
  File "/home/trolleway/.qgis2/python/plugins/ngw_connect/ngw_api/core/ngw_resource.py", line 66, in __init__
    self._construct()
  File "/home/trolleway/.qgis2/python/plugins/ngw_connect/ngw_api/core/ngw_wfs_service.py", line 35, in _construct
    if self.wfs.layers:
AttributeError: Wrapper instance has no attribute 'layers'


Версия Python:
2.7.6 (default, Jun 22 2015, 18:01:27) 
[GCC 4.8.2]


Версия:
2.10.0-Pisa Pisa, exported

Путь поиска Python: ['/home/trolleway/.qgis2/python/plugins/processing', '/home/trolleway/.qgis2/python/plugins/GeoCoding/libs', '/usr/share/qgis/python', u'/home/trolleway/.qgis2/python', u'/home/trolleway/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/usr/local/lib/python2.7/dist-packages/Genshi-0.7-py2.7-linux-x86_64.egg', '/usr/local/lib/python2.7/dist-packages/dbfpy-2.3.0-py2.7.egg', '/home/trolleway/ngw/nextgisweb', '/usr/local/lib/python2.7/dist-packages/GDAL-2.0.1-py2.7-linux-x86_64.egg', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', u'/home/trolleway/.qgis2//python', '/usr/share/qgis/python/plugins/fTools/tools']

```

**Comment by simgislab** [comment]
закрываю, что-то очень старое
