### ISSUE TITLE
Bug in update resource children

### ISSUE THREAD

**Issue by alisovenko** [nextgis/nextgis_connect#114]
Traceback (most recent call last):
  File "...\NextGIS QGIS/python/plugins\nextgis_connect\ngw_api\qt\qt_ngw_resource_base_model.py", line 128, in wrapper
    method(self, job)
  File "...\NextGIS QGIS/python/plugins\nextgis_connect\ngw_api\qt\qt_ngw_resource_base_model.py", line 439, in _updateResource
    for i in range(0, item.childCount()):
UnboundLocalError: local variable 'item' referenced before assignment

**Comment by alisovenko** [comment]
Fixed in 0.10.6
