### ISSUE TITLE
Catch NGW errors

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_connect#15]
Example:

>Traceback (most recent call last):
  File "C:\Users\sim\NextGIS QGIS/python/plugins\ngw_connect\tree_panel.py", line 356, in action_import_layer
    self._resource_model.createNGWLayer(qgs_map_layer, sel_index)
  File "C:\Users\sim\NextGIS QGIS/python/plugins\ngw_connect\ngw_api\qgis\ngw_resource_model_4qgis.py", line 88, in createNGWLayer
    qgs_map_layer.name()
  File "C:\Users\sim\NextGIS QGIS/python/plugins\ngw_connect\ngw_api\core\ngw_resource_creator.py", line 83, in create_vector_layer
    result = connection.post(url, params=params)
  File "C:\Users\sim\NextGIS QGIS/python/plugins\ngw_connect\ngw_api\core\ngw_connection.py", line 89, in post
    return self.__request(sub_url, 'POST', params, **kwargs)
  File "C:\Users\sim\NextGIS QGIS/python/plugins\ngw_connect\ngw_api\core\ngw_connection.py", line 81, in __request
    raise NGWError(resp.content)
NGWError: {"exception": "ForbiddenError", "message": "", "attr": "parent", "serializer": "resource"}

Should probably look like an Error window with some message (well in this case - empty?)

**Comment by alisovenko** [comment]
The feature is present in version 0.5.1
