### ISSUE TITLE
Ошибка питона

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgis_connect#50]
Установленная версия: 0.6.0

```
Ошибка при выполнении сценария Python:


Traceback (most recent call last):
  File "/home/bishop/.qgis2/python/plugins/nextgis_connect/tree_panel.py", line 258, in __checkImportActions
    elif isinstance(current_qgis_layer, (QgsVectorLayer, QgsRasterLayer)):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types


Версия Python:
2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160413]


Версия:
2.8.6-Wien Wien, exported

Путь поиска Python: ['/home/bishop/.qgis2/python/plugins/processing', '/usr/share/qgis/python', u'/home/bishop/.qgis2/python', u'/home/bishop/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/bishop/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/wx-3.0-gtk2', u'/home/bishop/.qgis2//python', '/home/bishop/.qgis2/python/plugins/DigitizingTools/tools', '/usr/share/qgis/python/plugins/fTools/tools']
```

**Comment by BishopGIS** [comment]
И снова ошибка, уже на 0.7.4
```
An error has occurred while executing Python code:


Traceback (most recent call last):
  File "/home/bishop/.qgis2/python/plugins/nextgis_connect/tree_panel.py", line 262, in __checkImportActions
    elif isinstance(current_qgis_layer, (QgsVectorLayer, QgsRasterLayer)):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types


Python version:
2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160413]


QGIS version:
2.8.6-Wien Wien, exported

Python path: ['/home/bishop/.qgis2/python/plugins/processing', '/usr/share/qgis/python', u'/home/bishop/.qgis2/python', u'/home/bishop/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/bishop/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/wx-3.0-gtk2', u'/home/bishop/.qgis2//python', '/home/bishop/.qgis2/python/plugins/DigitizingTools/tools', '/usr/share/qgis/python/plugins/fTools/tools']
```
