### ISSUE TITLE
TypeError: decoding Unicode is not supported 

### ISSUE THREAD

**Issue by drnextgis** [nextgis/nextgis_connect#83]
```
TypeError: decoding Unicode is not supported 
Traceback (most recent call last):
  File "/home/rykov/.qgis2/python/plugins/nextgis_connect/tree_panel.py", line 493, in __export_to_qgis
    add_resource_as_geojson(ngw_resource)
  File "/home/rykov/.qgis2/python/plugins/nextgis_connect/ngw_api/qgis/resource_to_map.py", line 34, in add_resource_as_geojson
    raise NGWError('Layer %s can\'t be added to the map!' % resource.common.display_name)
  File "/home/rykov/.qgis2/python/plugins/nextgis_connect/ngw_api/core/ngw_error.py", line 25, in __init__
    self.message = unicode(message, 'utf-8')
TypeError: decoding Unicode is not supported
```

**Comment by kid-fenix** [comment]
Traceback (most recent call last):
			  File "c:/NEXTGI 1/apps/qgis/./python/plugins\nextgis_connect\tree_panel.py", line 467, in __export_to_qgis
			    add_resource_as_geojson(ngw_resource)
			  File "c:/NEXTGI 1/apps/qgis/./python/plugins\nextgis_connect\ngw_api\qgis\resource_to_map.py", line 34, in add_resource_as_geojson
			    raise NGWError('Layer %s can\'t be added to the map!' % resource.common.display_name)
			  File "c:/NEXTGI~1/apps/qgis/./python/plugins\nextgis_connect\ngw_api\core\ngw_error.py", line 25, in __init__
			    self.message = unicode(message, 'utf-8')
			TypeError: decoding Unicode is not supported
