### ISSUE TITLE
Невозможно создать новое подключение

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgis_connect#91]
```
Ошибка при выполнении сценария Python: 

TypeError: findText(self, QString, flags: Qt.MatchFlags = Qt.MatchExactly|Qt.MatchCaseSensitive): argument 1 has unexpected type 'QPyNullVariant' 
Traceback (most recent call last):
  File "/Users/bishop/.qgis2/python/plugins/nextgis_connect/tree_panel.py", line 436, in action_settings
    sett_dialog = SettingsDialog()
  File "/Users/bishop/.qgis2/python/plugins/nextgis_connect/settings_dialog.py", line 55, in __init__
    self.populate_connection_list()
  File "/Users/bishop/.qgis2/python/plugins/nextgis_connect/settings_dialog.py", line 106, in populate_connection_list
    idx = self.cmbConnections.findText(last_connection)
TypeError: findText(self, QString, flags: Qt.MatchFlags = Qt.MatchExactly|Qt.MatchCaseSensitive): argument 1 has unexpected type 'QPyNullVariant'


Версия Python: 2.7.10 (default, Jul 30 2016, 18:31:42) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] 
Версия: 2.14.7-Essen Essen, exported 

Расположение Python:
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/bishop/.qgis2/python
/Users/bishop/.qgis2/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7
/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7/site-packages
/Library/Python/2.7/site-packages/numpy-override
/Library/Python/2.7/site-packages/matplotlib-override
/Library/Frameworks/GDAL.framework/Versions/2.1/Python/2.7/site-packages
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
/Library/Python/2.7/site-packages
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
/Users/bishop/.qgis2//python
/Applications/QGIS.app/Contents/Resources/python/plugins/fTools/tools
```

**Comment by simgislab** [comment]
дело происходит на абсолютно новой машине где не было ни кугиса (вроде) ни (точно) коннекта до этого
